config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/', to: 'static#index', as: :home

  # Documents
  get '/documents', to: 'document#index', as: :documents
  get '/documents/unit/:unit(/:type)', to: 'document#unit',
      as: :documents_unit

  # Errors
  get '/404', to: 'errors#not_found'
  get '/422', to: 'errors#unacceptable'
  get '/500', to: 'errors#internal_error'

  # Explore
  get '/explore', to: 'explore#index', as: :explore
  get '/explore/map', to: 'explore#map', as: :map
  get '/explore/units', to: 'explore#units', as: :units
  get '/explore/unit/:number', to: 'explore#unit_summary', as: :unit
  get '/explore/unit/:number/overview', to: 'explore#unit_overview',
      as: :unit_overview
  get '/explore/unit/:number/images', to: 'explore#unit_images',
      as: :unit_images
  get '/explore/unit/:number/documents', to: 'explore#unit_documents',
      as: :unit_documents
  get '/explore/unit/:number/strata', to: 'explore#unit_strata',
      as: :unit_strata
  get '/explore/unit/:number/associated', to: 'explore#unit_associated',
      as: :unit_associated
  get '/explore/zone/:number', to: 'explore#zone', as: :search_zone

  # Images
  get '/gallery', to: 'image#index', as: :gallery
  get '/gallery/:number', to: 'image#show', as: :image

  # Query
  get '/query', to: 'query#index', as: :query
  get '/query/other', to: 'query#other', as: :query_other
  get '/query/:category', to: 'query#category', as: :query_category
  get '/query/:category/:subcat(/:table)', to: 'query#form', as: :query_form
  get '/query/:category/:subcat/:table/results', to: 'query#results',
      as: :query_results

  # Static Pages
  get '/about', to: 'static#about', as: :about
  get '/about/:name', to: 'static#about_sub', as: :about_sub
  get '/native-descendants', to: 'static#descendants', as: :descendants

end

app/controllers/query/bone_inventories_controller.rb
class Query::BoneInventoriesController < ApplicationController

  active_scaffold :bone_inventory do |conf|
    conf.columns = [:site, :units, :strata, :features, :fs, :box, :bone_inventory_count, :gridew, :gridns, :quad, :exactprov, :depthbeg, :depthend, :stratalpha, :strat_one, :strat_two, :othstrats, :field_date, :excavator, :art_type, :sano, :recordkey, :comments, :entby, :location]
    conf.update.columns = [:site, :fs, :box, :bone_inventory_count, :gridew, :gridns, :quad, :exactprov, :depthbeg, :depthend, :stratalpha, :strat_one, :strat_two, :othstrats, :field_date, :excavator, :art_type, :sano, :recordkey, :comments, :entby, :location]
    # conf.columns[:art_type].form_ui = :select
    conf.actions.swap :search, :field_search
  end

end

app/controllers/query/bone_tools_controller.rb
class Query::BoneToolsController < ApplicationController

  active_scaffold :bone_tool do |conf|
    conf.columns = [:units, :strata, :field_specimen_no, :depth, :bone_tool_occupation, :grid, :tool_type_code, :tool_type, :species_code, :comments]
    conf.columns[:bone_tool_occupation].form_ui = :select
    # conf.columns[:strata].form_ui = :record_select
    # conf.columns[:features].options = {:draggable_lists => true}
    conf.actions.swap :search, :field_search
  end


end

app/controllers/query/ceramic_inventories_controller.rb
class Query::CeramicInventoriesController < ApplicationController

  active_scaffold :ceramic_inventory do |conf|
    conf.columns = [:site, :units, :strata, :features, :fs, :box, :ceramic_inventory_count, :gridew, :gridns, :quad, :exactprov, :depthbeg, :depthend, :stratalpha, :strat_one, :strat_two, :othstrats, :field_date, :excavator, :art_type, :sano, :recordkey, :comments, :entby, :location]
    conf.update.columns = [:site, :fs, :box, :ceramic_inventory_count, :gridew, :gridns, :quad, :exactprov, :depthbeg, :depthend, :stratalpha, :strat_one, :strat_two, :othstrats, :field_date, :excavator, :art_type, :sano, :recordkey, :comments, :entby, :location]
    # conf.columns[:art_type].form_ui = :select
    conf.actions.swap :search, :field_search
  end

end

app/controllers/query/eggshells_controller.rb
class Query::EggshellsController < ApplicationController

  active_scaffold :eggshell do |conf|
    conf.columns = [:units, :strata, :features, :salmon_museum_id_no, :record_field_key_no, :grid, :depth, :feature_no, :storage_bin, :museum_date, :field_date, :eggshell_affiliation, :eggshell_item]
    conf.columns[:eggshell_affiliation].form_ui = :select
    conf.columns[:eggshell_item].form_ui = :select
    conf.actions.swap :search, :field_search
  end


end

app/controllers/query/features_controller.rb
class Query::FeaturesController < ApplicationController

  active_scaffold :feature do |conf|
    
    conf.columns = [:units, :strata, :unit_no, :feature_no, :floor_association, :feature_form, :other_associated_features, :grid, :depth_m_b_d, :feature_occupation, :feature_type, :feature_count, :feature_group, :residential_feature, :location_in_room, :t_shaped_door, :door_between_multiple_room, :doorway_sealed, :length, :width, :depth_height, :comments]
    conf.columns[:feature_occupation].form_ui = :select
    conf.columns[:feature_type].form_ui = :select
    conf.columns[:feature_group].form_ui = :select
    conf.columns[:residential_feature].form_ui = :select
    conf.columns[:t_shaped_door].form_ui = :select
    conf.columns[:door_between_multiple_room].form_ui = :select
    conf.columns[:doorway_sealed].form_ui = :select
    conf.columns[:length].label  = 'Length'
    conf.columns[:width].label  = 'Width'
    conf.columns[:depth_height].label  = 'Depth/Height'
    conf.actions.swap :search, :field_search
  end

  record_select :per_page => 10, :search_on => [:feature_no]

end

app/controllers/query/lithic_inventories_controller.rb
class Query::LithicInventoriesController < ApplicationController

  active_scaffold :lithic_inventory do |conf|
    conf.columns = [:site, :units, :strata, :features, :fs, :box, :lithic_inventory_count, :gridew, :gridns, :quad, :exactprov, :depthbeg, :depthend, :stratalpha, :strat_one, :strat_two, :othstrats, :field_date, :excavator, :art_type, :sano, :recordkey, :comments, :entby, :location]
    conf.update.columns = [:site, :fs, :box, :lithic_inventory_count, :gridew, :gridns, :quad, :exactprov, :depthbeg, :depthend, :stratalpha, :strat_one, :strat_two, :othstrats, :field_date, :excavator, :art_type, :sano, :recordkey, :comments, :entby, :location]
    # conf.columns[:art_type].form_ui = :select
    conf.actions.swap :search, :field_search
  end

end

app/controllers/query/ornaments_controller.rb
class Query::OrnamentsController < ApplicationController

  active_scaffold :ornament do |conf|
    conf.columns = [:units, :strata, :feature, :museum_specimen_no, :analysis_lab_no, :grid, :quad, :depth, :field_date, :ornament_period, :analyst, :analyzed, :photographer, :count, :item]
    conf.columns[:ornament_period].form_ui = :select
    conf.actions.swap :search, :field_search
  end


end

app/controllers/query/perishables_controller.rb
class Query::PerishablesController < ApplicationController

  active_scaffold :perishable do |conf|
    conf.columns = [:units, :strata, :features, :fs_number, :salmon_museum_number, :grid, :quad, :depth, :perishable_period, :sa_no, :artifact_type, :perishable_count, :artifact_structure, :comments, :other_comments, :storage_location, :exhibit_location, :record_key_no, :museum_lab_no, :field_date, :original_analysis]
    conf.columns[:perishable_period].form_ui = :select
    conf.actions.swap :search, :field_search
  end


end

app/controllers/query/room_types_controller.rb
class Query::RoomTypesController < ApplicationController

  active_scaffold :room_type do |conf|
    conf.columns = [:description, :period, :location]
  end

  record_select :per_page => 10, :search_on => [:description, :period, :location]


end

app/controllers/query/select_artifacts_controller.rb
class Query::SelectArtifactsController < ApplicationController

  active_scaffold :select_artifact do |conf|
    conf.columns = [:units, :strata, :artifact_no, :floor_association, :sa_form, :associated_feature_artifacts, :grid, :depth, :select_artifact_occupation, :select_artifact_type, :artifact_count, :location_in_room, :comments]
    conf.columns[:select_artifact_occupation].form_ui = :select
    conf.actions.swap :search, :field_search
  end


end

app/controllers/query/soils_controller.rb
class Query::SoilsController < ApplicationController

  active_scaffold :soil do |conf|
    conf.columns = [:site, :units, :strata, :features, :fs, :box, :period, :soil_count, :gridew, :gridns, :quad, :exactprov, :depthbeg, :depthend, :otherstrat, :date, :excavator, :art_type, :sample_no, :comments, :data_entry, :location]
    conf.columns[:art_type].form_ui = :select
    conf.actions.swap :search, :field_search
  end

end

app/controllers/query/strata_controller.rb
class Query::StrataController < ApplicationController

  active_scaffold :stratum do |conf|
    # conf.columns[:room].label = 'Unit'
    # conf.columns[:room_no].label = 'Unit no.'
    conf.columns = [:unit, :strat_all, :strat_alpha, :strat_type, :stratum_one, :stratum_two, :strat_occupation, :features, :comments] #, :features, :bone_tools, :eggshells]
    conf.columns[:unit].actions_for_association_links = [:show]
    conf.columns[:strat_type].form_ui = :select
    conf.columns[:strat_occupation].form_ui = :select
    conf.actions.swap :search, :field_search
  end

  record_select :per_page => 10, :search_on => [:strat_all], :order_by => 'strat_all asc, strat_alpha asc'

end

app/controllers/query/units_controller.rb
class Query::UnitsController < ApplicationController

  active_scaffold :unit do |conf|
    conf.label = 'Units'
    conf.columns = [:unit_no, :excavation_status, :unit_occupation, :unit_class, :story, :intact_roof, :room_type, :type_description, :inferred_function, :salmon_sector, :other_description, :irregular_shape, :length, :width, :floor_area, :comments, :strata]
    conf.update.columns = [:unit_no, :excavation_status, :unit_occupation, :unit_class, :story, :intact_roof, :room_type, :type_description, :inferred_function, :salmon_sector, :other_description, :irregular_shape, :length, :width, :floor_area, :comments]
    # conf.columns[:codexes].label = 'Strata'
    conf.columns[:excavation_status].form_ui = :select
    conf.columns[:unit_occupation].form_ui = :select
    conf.columns[:unit_class].form_ui = :select
    conf.columns[:story].form_ui = :select
    conf.columns[:intact_roof].form_ui = :select
    conf.columns[:room_type].form_ui = :select
    conf.columns[:type_description].form_ui = :select
    conf.columns[:inferred_function].form_ui = :select
    conf.columns[:salmon_sector].form_ui = :select
    conf.columns[:irregular_shape].form_ui = :select
    conf.columns[:room_type].form_ui = :record_select
    conf.columns[:room_type].actions_for_association_links = [:show]
    # conf.columns[:other_desc].options = {:rows => 5, :cols => 60}
    # conf.columns[:comments].options = {:rows => 5, :cols => 60}

    conf.columns[:strata].form_ui = :record_select

    conf.actions.swap :search, :field_search
    # conf.field_search.columns = [:room_no, :excavation_status, :occupation, :room_class, :stories, :intact_roof, :room_type, :type_description, :inferred_function, :salmon_sector, :other_desc, :irregular_shape, :length_text, :width_text, :floor_area_text, :comments, :codexes]
    conf.field_search.columns = [:unit_no, :excavation_status, :unit_occupation] #, :unit_class, :story, :intact_roof, :room_type, :type_description, :inferred_function, :salmon_sector, :other_description, :irregular_shape, :length, :width, :floor_area, :comments, :strata]
  end

  record_select :per_page => 10, :search_on => [:unit_no]

end

app/helpers/query_helper.rb
module QueryHelper
  include ActiveRecordAbstraction

  def checked?(value, paramlist)
    if paramlist.blank?
      return false
    else
      return paramlist.include?(value.to_s)
    end
  end

  def common_search_expand(param, first: false)
    if first
      if session[:common_search_unit].blank? &&
        session[:common_search_unit_class].blank? &&
        session[:common_search_occupation].blank? &&
        session[:common_search_strat_grouping].blank? &&
        session[:common_search_feature_group].blank?

        return 'in'
      end
    end

    if @search_expanded || param.blank? || param.empty?
      ''
    else
      @search_expanded = true
      'in'
    end
  end

  def delimit(number)
    number_with_delimiter(number)
  end

  def params_copy
    # create a new object so that the params
    # are not directly altered
    params.to_unsafe_h
  end

  def select_from_assoc(column, param_name)
    # Check if model defines column to use instead of default "name"
    if column[:name].classify.constantize.respond_to?("abstraction")
      model = column[:name].classify.constantize
      abstraction = model.send("abstraction")
      select_tag param_name,
                 options_from_collection_for_select(
                   model.distinct.order(abstraction[:assoc_input_column]),
                   "id", abstraction[:assoc_input_column], params[param_name]
                 ),
                 class: "form-control", include_blank: true
    else
      select_tag param_name,
                 options_from_collection_for_select(
                   column[:name].classify.constantize.distinct.order(:name),
                   "id", "name", params[param_name]
                 ),
                 class: "form-control", include_blank: true
    end
  end

  def select_from_column(model_class, column, param_name)
    select_tag param_name,
               options_for_select(model_class.pluck(column[:name]).compact
                                    .uniq.sort,
                                  params[param_name]),
               class: "form-control", include_blank: true
  end

  def select_from_join(model_class, column, param_name)
    select_tag param_name,
               options_for_select(model_class.joins(column[:join_table])
                                           .pluck(column[:name])
                                           .uniq.sort,
                                  params[param_name]),
               class: "form-control", include_blank: true
  end

end

app/views/query/_common_fields.html.erb
<%= javascript_include_tag "query" %>

<h4>Common Search Options</h4>

<span class="common_search_help glyphicon glyphicon-question-sign"
  aria-hidden="true" data-toggle="popover"
  data-content="If no selections are made in a group, results will not be
    narrowed by that criteria. Common Search Options are saved when a search is
    performed. To clear all saved search options, press the 'Clear All Search
    Options' button. Note: This will also clear any search criteria entered in
    the table search options to the right.">
</span>
<div class="pull-right">
  <%= link_to "Clear All Search Options", { controller: params["controller"],
    action: params["action"], search_clear: 1 }, class: "btn btn-danger" %>
</div>
<div class="clearfix buffer-bottom-sm"></div>

<!-- common search options accordian -->
<% @search_expanded = false %>
<div class="panel-group combined_selections" id="accordion" role="tablist" aria-multiselectable="true">

  <!-- unit type filters -->
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="heading-unitclass">
      <h4 class="panel-title">
        <a role="button" data-toggle="collapse" data-parent="#accordion"
           href="#collapse-unitclass" aria-expanded="true" aria-controls="collapse-unitclass">
          Unit Type
        </a>
        <% search_param = session[:common_search_unit_class] %>
        <%= render "common_search_badge", session_value: search_param %>
      </h4>
    </div>
    <div id="collapse-unitclass" class="panel-collapse collapse
      <%= common_search_expand(search_param, first: true) %>" role="tabpanel"
      aria-labelledby="heading-unit">
      <div>
        <ul class="list-group checked-list-box">
          <% UnitClass.sorted.each do |u| %>
            <li class="list-group-item">
              <div class="form-inline">
                <div class="checkbox">
                  <%= check_box_tag "unit_class[#{u.id}]", u.id, checked?(u.id, session[:common_search_unit_class]), class: "select_all", name: "unit_class_common[]" %>
                  <%= label_tag "unit_class[#{u.id}]", u.name.titleize %>
                </div>
              </div>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>

  <!-- unit num filters -->
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="heading-unitnum">
      <h4 class="panel-title">
        <a role="button" data-toggle="collapse" data-parent="#accordion"
           href="#collapse-unitnum" aria-expanded="false" aria-controls="collapse-unitnum">
          Unit Number
        </a>
        <% search_param = session[:common_search_unit] %>
        <%= render "common_search_badge", session_value: search_param %>
      </h4>
    </div>
    <div id="collapse-unitnum" class="panel-collapse collapse
      <%= common_search_expand(search_param) %>" role="tabpanel"
      aria-labelledby="heading-num">
      <div>
        <ul class="list-group checked-list-box">
          <% Unit.sorted.each do |u| %>
            <li class="list-group-item">
              <div class="form-inline">
                <div class="checkbox">
                  <%= check_box_tag "unit[#{u.id}]", u.id, checked?(u.id, session[:common_search_unit]), class: "select_all", name: "unit_common[]" %>
                  <%= label_tag "unit[#{u.id}]", u.unit_no %>
                </div>
              </div>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>

  <!-- occupation filters -->
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="heading-occupation">
      <h4 class="panel-title">
        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion"
           href="#collapse-occupation" aria-expanded="false" aria-controls="collapse-occupation">
          Occupation
        </a>
        <% search_param = session[:common_search_occupation] %>
        <%= render "common_search_badge", session_value: search_param %>
      </h4>
    </div>
    <div id="collapse-occupation" class="panel-collapse collapse
      <%= common_search_expand(search_param) %>" role="tabpanel"
      aria-labelledby="heading-occupation">
      <div>
        <ul class="list-group checked-list-box">
          <% Occupation.sorted.each do |o| %>
            <li class="list-group-item">
              <div class="form-inline">
                <div class="checkbox">
                  <%= check_box_tag "occupation[#{o.id}]", o.id,
                    checked?(o.id, session[:common_search_occupation]), class:
                    "select_all", name: "occupation_common[]" %>
                  <%= label_tag "occupation[#{o.id}]", o.name.titleize %>
                </div>
              </div>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>

  <!-- strata filters -->
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="heading-stratum">
      <h4 class="panel-title">
        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse-stratum" aria-expanded="false" aria-controls="collapse-stratum">
          Strata
        </a>
        <% search_param = session[:common_search_strat_grouping] %>
        <%= render "common_search_badge", session_value: search_param %>
      </h4>
    </div>
    <div id="collapse-stratum" class="panel-collapse collapse
      <%= common_search_expand(search_param) %>" role="tabpanel"
      aria-labelledby="heading-stratum">
      <div>
        <ul class="list-group checked-list-box">
          <% StratGrouping.sorted.each do |s| %>
            <li class="list-group-item">
              <div class="form-inline">
                <div class="checkbox">
                  <%= check_box_tag "strat_grouping[#{s.id}]", s.id, checked?(s.id, session[:common_search_strat_grouping]),
                    class: "select_all", name: "strat_grouping[]" %>
                  <%= label_tag "strat_grouping[#{s.id}]", s.name.titleize %>
                </div>
              </div>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>

  <!-- features filters -->
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="heading-feature">
      <h4 class="panel-title">
        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion"
           href="#collapse-feature" aria-expanded="false" aria-controls="collapse-feature">
          Feature
        </a>
        <% search_param = session[:common_search_feature_group] %>
        <%= render "common_search_badge", session_value: search_param %>
      </h4>
    </div>
    <div id="collapse-feature" class="panel-collapse collapse
      <%= common_search_expand(search_param) %>" role="tabpanel"
      aria-labelledby="heading-feature">
      <div>
        <ul class="list-group checked-list-box">
          <% FeatureGroup.sorted.each do |fg| %>
            <li class="list-group-item">
              <div class="form-inline">
                <div class="checkbox">
                  <%= check_box_tag "feature_group[#{fg.id}]", fg.id,
                    checked?(fg.id, session[:common_search_feature_group]),
                    class: "select_all", name: "feature_group_common[]" %>
                  <%= label_tag "feature_group[#{fg.id}]", fg.name.titleize %>
                </div>
              </div>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/query/_common_search_badge.html.erb
<span
  <% if session_value.present? %>
    class="pull-right badge" aria-hidden="false"
  <% else %>
    class="pull-right badge hidden" aria-hidden="true"
  <% end %>
  title="Options selected">
  <%= session_value.present? ? session_value.size : 0 %>
</span>

app/views/query/_csv_results_download.html.erb
<%= link_to query_results_path(params_copy.merge(format: "csv")) do %>
  <button type="button" class="btn btn-default">
    Download as CSV <span class="glyphicon glyphicon-download-alt"></span>
  </button>
<% end %>

app/views/query/_csv_table_download.html.erb
<%= link_to query_results_path(
  all: 1,
  category: params["category"],
  format: "csv",
  table: params["table"],
  subcat: params["subcat"]
  ) do %>
  <button type="button" class="btn btn-default">
    Download entire table as CSV <span class="glyphicon glyphicon-download-alt"></span>
  </button>
<% end %>

app/views/query/form.html.erb
<h2><%= params[:category].titleize %> Search</h2>

<%= form_tag query_results_path(params[:category], params[:subcat], params[:table]), method: :get do %>
  <div class="row">
    <div class="col-md-4">
      <%= render "common_fields" %>
    </div>

    <div class="col-md-8">
      <% if !params[:category][/^(?:units|features|strata|images)$/] %>
        <%= abstraction_subnav %>
      <% end %>

      <ul class="nav nav-tabs buffer-bottom">
        <% @tables.each do |t| %>
          <li class="<%= active?(params[:table], t[:name])%>">
          <%= link_to query_form_path(params[:category], params[:subcat],
                                      t[:name]) do %>
            <%= t[:label] %>
            <span class="badge"><%= delimit(t[:count]) %></span>
          <% end %>
          </li>
        <% end %>
      </ul>

      <p class="buffer-bottom" id="query_table_description">
        <%= table_description %>
      </p>

      <div class="query_description_display">
        <button class="btn btn-info btn-sm" type="button" data-toggle="collapse" data-target="#query_table_description" aria-expanded="false" aria-controls="Show table description" id="query_desc_disp_btn">Show table description</button>
      </div>

      <div class="clearfix"></div>
      
      <div class="row">
        <div class="col-md-8">
          <%= render "csv_table_download" %>
        </div>
        <div class="col-md-4">
          <%= submit_tag "Search #{table_label}", class: "btn btn-primary pull-right" %>
        </div>
      </div>
      
      <div class="row">
        <%= display_forms @table_fields[:primary] %>
      </div>
      
      <div class="query_other_otions_btn_wrap">
        <button class="btn btn-info btn-sm" type="button" data-toggle="collapse" data-target="#query_other_otions" aria-expanded="false" aria-controls="Show search options" id="query_search_options_btn">Show more search options</button>
      </div>

      <div class="row well" id="query_other_otions">
        <%= display_forms @table_fields[:other] %>
      </div>
      
      <div class="pull-right">
        <%= submit_tag "Search #{table_label}", class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/query/other.html.erb
<h2>Other Tables</h2>

<p class="lead">Three additional data tables are not accessible within in the SPARC relational database.</p>

<p><strong>Select Artifacts:</strong>  This analysis table contains data on "significant artifacts" identified during fieldwork at Salmon during the 1970s and given separate tracking numbers. During Archaeology Southwest's Salmon Project (2001-2018), these data were checked and the table was edited. In a few cases, new numbers were assigned to match forms in the archive that lacked numbers.

<p>As its name ("Select Artifacts") suggests, this is not an exhaustive inventory of all point-provenienced or otherwise special artifacts. This table contains specific artifact descriptions that are not included in other tables. To resolve this, the SPARC team dissolved the SA table by matching FS #s and other contextual information from the SA table with other records in the database.  When matches were found, information from the SA table was added to the matching record in the other table (e.g., the ornament table).  This allowed us to retain the unique information recorded in the SA table without creating duplicate records.

<p>It is also the case that some items recorded in the “Select Artifacts” table were never listed in any other inventory or analysis table.  For instance, an ornament might have been recorded in the SA table, but did not exist in the "Ornament" table.  Users may, therefore, be interested in downloading the entire Select Artifacts table. </p>

<p><%= link_to query_other_path({ format: "csv" }) do %>
      <button type="button" class="btn btn-default">
        Download select artifacts as CSV <span class="glyphicon glyphicon-download-alt"></span>
      </button>
  <% end %>
</p>

<p>The Salmon Ruins Museum has two other data tables that are not included within SPARC due to the sensitive nature of their contents:  A human burial table and a human osteology table. Qualified individuals may request access to this information. Please note, such requests will be granted at the discretion of the Director of the Salmon Ruins Museum. All inquiries should be directed to:</p>

<p>Larry Baker<br/>
Salmon Ruins Museum<br/>
P. O. Box 125<br/>
Bloomfield, NM  87413<br/>
sreducation[at]sisna.com&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;505-632-2013</p>

app/views/query/query_form.html.erb
<h3>Artifact Search</h3>

<%= form_tag query_results_path(params[:category], params[:type], params[:table]), method: :get do %>
  <div class="row">
    <div class="col-md-4">
      <%= render "global_fields" %>
    </div>

    <div class="col-md-8">
      <%= render "artifacts_nav" %>

      <%# if @tables.size > 1 %>
        <ul class="nav nav-tabs buffer-bottom">
          <% @tables.each_with_index do |t, index| %>
            <li class="<%= active?(params[:table], t[:name].to_s)%>">
            <%= link_to query_form_path(params[:category], params[:type],
                                        t[:name]) do %>
              <%= t[:label] %>
              <span class="badge"><%= delimit(t[:count]) %></span>
            <% end %>
            </li>
          <% end %>
        </ul>
      <%# end %>

      <div class="pull-right">
        <%= submit_tag "Search #{params[:table].to_s.pluralize.titleize}",
                       class: "btn btn-primary" %>
      </div>
      <div class="clearfix"></div>

      <div class="row">
        <!-- Text fields -->
        <div class="col-md-6">
          <% @table_inputs.each do |column| %>
            <div class="form-group">
              <%= label_tag column[:name], column[:name].titleize %>
              <%= text_field_tag column[:name], params[column[:name]],
                                 class: "form-control" %>
            </div>
          <% end %>
        </div>

        <!-- Select fields -->
        <div class="col-md-6">
          <% @table_selects.each do |column| %>
            <% param_name = "inv_#{column[:name]}" %>
            <div class="form-group">
              <%= label_tag column[:name], column[:name].titleize %>
              <% if column[:type] == :column %>
                <%= select_from_column @table_class, column, column[:name] %>
              <% elsif column[:type] == :assoc %>
                <%= select_from_assoc column, column[:name] %>
              <% end %>
             </div>
          <% end %>
        </div>
      </div>

      <div class="pull-right">
        <%= submit_tag "Search #{params[:table].to_s.pluralize.titleize}",
                       class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>