config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/', to: 'static#index', as: :home

  # Documents
  get '/documents', to: 'document#index', as: :documents
  get '/documents/unit/:unit(/:type)', to: 'document#unit',
      as: :documents_unit

  # Errors
  get '/404', to: 'errors#not_found'
  get '/422', to: 'errors#unacceptable'
  get '/500', to: 'errors#internal_error'

  # Explore
  get '/explore', to: 'explore#index', as: :explore
  get '/explore/map', to: 'explore#map', as: :map
  get '/explore/units', to: 'explore#units', as: :units
  get '/explore/unit/:number', to: 'explore#unit_summary', as: :unit
  get '/explore/unit/:number/overview', to: 'explore#unit_overview',
      as: :unit_overview
  get '/explore/unit/:number/images', to: 'explore#unit_images',
      as: :unit_images
  get '/explore/unit/:number/documents', to: 'explore#unit_documents',
      as: :unit_documents
  get '/explore/unit/:number/strata', to: 'explore#unit_strata',
      as: :unit_strata
  get '/explore/unit/:number/associated', to: 'explore#unit_associated',
      as: :unit_associated
  get '/explore/zone/:number', to: 'explore#zone', as: :search_zone

  # Images
  get '/gallery', to: 'image#index', as: :gallery
  get '/gallery/:number', to: 'image#show', as: :image

  # Query
  get '/query', to: 'query#index', as: :query
  get '/query/other', to: 'query#other', as: :query_other
  get '/query/:category', to: 'query#category', as: :query_category
  get '/query/:category/:subcat(/:table)', to: 'query#form', as: :query_form
  get '/query/:category/:subcat/:table/results', to: 'query#results',
      as: :query_results

  # Static Pages
  get '/about', to: 'static#about', as: :about
  get '/about/:name', to: 'static#about_sub', as: :about_sub
  get '/native-descendants', to: 'static#descendants', as: :descendants

end

app/models/image.rb
class Image < ActiveRecord::Base
  has_and_belongs_to_many :features
  has_many :strata, -> {distinct}, :through => :features
  has_many :units, -> {distinct}, :through => :strata
  has_many :zones, -> {distinct}, :through => :units

  has_and_belongs_to_many :image_subjects
  belongs_to :image_box
  belongs_to :image_creator
  belongs_to :image_format
  belongs_to :image_human_remain
  belongs_to :image_orientation
  belongs_to :image_quality

  if SETTINGS["hide_sensitive_image_records"]
    default_scope {
      joins(:image_human_remain).where(image_human_remains: { displayable: true })
    }
  end

  def self.abstraction
    {
      assoc_col: "image_no",
      description: <<-DESC,
The Images table was created by Nancy Espinosa, Emma Gibson, and other staff
members (of Salmon Ruins Museum) as part of Archaeology Southwest's Salmon
Project (2001-2018). This table contains data on images (photographic prints,
slides, polaroids from fieldwork, map transparencies, etc.) from the 1970s
Salmon Project. During the SPARC project (2015-2018), data within this table
were edited and cross-checked against other sources.
      DESC
      disabled: %w[],
      labels: {
        image_no: "Image Number",
        image_orientation: "Orientation",
        image_subjects: "Subjects"
      },
      primary: %w[
        image_no image_format image_orientation image_subjects comments
      ],
      selects: %w[image_format image_orientation image_subjects]
    }
  end

  def self.sorted
    order("images.image_no")
  end

  def to_label
    image_no
  end

  def box
    image_box.name if image_box
  end

  def creator
    image_creator.name if image_creator
  end

  def displayable?
    no_remains = true
    no_remains = image_human_remain.displayable if image_human_remain
    no_remains && file_exists
  end

  def format
    image_format.name if image_format
  end

  def human_remain
    image_human_remain.name if image_human_remain
  end

  def orientation
    image_orientation.name if image_orientation
  end

  def filepath
    loc = format == "polaroid" ? "polaroids" : "field"
    # strip PA[0] from front of image names
    # since database image_no does not match filesystem
    filename = image_no.gsub(/^PA0?/, "")
    "#{loc}/#{filename}.jpg"
  end

  def quality
    image_quality.name if image_quality
  end

  def subject_list
    image_subjects.map {|s| s.name }
  end

  def unit_list
    units.map {|u| u.unit_no }
  end

  def zone_list
    zones.map {|z| z.name }
  end

end

app/controllers/image_controller.rb
class ImageController < ApplicationController
  before_action :set_section

  def index
    # always include these fields because they are used to describe each image
    images = Image.includes(
      :image_format,
      :image_human_remain,
      :image_subjects,
      :units,
    )
    images = images.where(file_exists: true)
    images = images.where("images.image_no LIKE ?", "%#{params['image_no']}%") if present?(params["image_no"])
    images = images.where("images.comments LIKE ?", "%#{params['comments']}%") if present?(params["comments"])
    images = add_to_query(images, :image_boxes, params["box"], :image_box, true)
    images = add_to_query(images, :image_creators, params["creator"], :image_creator, true)
    images = add_to_query(images, :image_formats, params["format"], :image_format, false)
    images = add_to_query(images, :image_human_remains, params["human_remain"], :image_human_remain, false)
    images = add_to_query(images, :image_orientations, params["orientation"], :image_orientation, true)
    images = add_to_query(images, :image_qualities, params["quality"], :image_quality, true)
    images = add_to_query(images, :image_subjects, params["subject"], :image_subjects, false)
    images = add_to_query(images, :units, params["unit"], :units, false)

    @result_num = images.size

    @images = images.paginate(:page => params[:page], :per_page => 20)
    @units = Unit.sorted.distinct.joins(:images).order("unit_no")
  end

  def show
    @image = Image.includes(:image_subjects, :units)
      .find_by(image_no: params[:number])
  end

  private

  # essentially creating: images.where(:where_rel => { :id => param }).joins(:relationship)
  # assumes that the tables need to be joined, but can optionally omit join if this table
  # has previously been loaded via includes
  def add_to_query(query_obj, where_rel, param, relationship, joins=true)
    if present?(param)
      query_obj = query_obj.where(where_rel => { :id => param })
      query_obj = query_obj.joins(relationship) if joins
    end
    return query_obj
  end

  def set_section
    @section = "images"
  end

end

app/helpers/image_helper.rb
module ImageHelper

  # default to true if not otherwise marked
  def human_remains? code
    code == "N" ? false : true
  end
  
end

app/views/image/index.html.erb
<h2>Image Gallery</h2>

<p>Search and browse all available SPARC images.</p> 

<p>Please note: Images showing human remains and known funerary items have been excluded from all image searches because of their cultural sensitivity.  Metadata about these images can be found using the <%= link_to "Image Query", query_category_path(category: "images") %>.</p>

<%= form_tag gallery_path, :method => "get",
  id: "image-search-form", role: "form" do %>
  <%= hidden_field_tag "sort", params["sort"] %>
  <!-- primary search fields -->
  <div class="row">
    <div class="col-sm-3">
      <div class="form-group">
        <%= label_tag "image_no", "Image No. (e.g. \"00946\")" %>
        <%= text_field_tag "image_no", params["image_no"], class: "form-control" %>
      </div>
      <div class="form-group">
        <%= label_tag "comments", "Comments (e.g. \"wall section\")" %>
        <%= text_area_tag "comments", params["comments"], rows: 2, class: "form-control" %>
      </div>
    </div>
    <div class="col-sm-2">
      <div class="form-group">
        <div class="form-group">
          <%= label_tag "unit", "Unit" %>
          <%= select_tag "unit", options_from_collection_for_select(Unit.sorted, "id", "unit_no", params["unit"]), class: "form-control", multiple: true, include_blank: true, size: 6 %>
        </div>
      </div>
    </div>
    <div class="col-sm-5">
      <div class="form-group">
        <div class="form-group">
          <%= label_tag "subject", "Subject" %>
          <%= select_tag "subject", options_from_collection_for_select(ImageSubject.sorted, "id", "name", params["subject"]), class: "form-control", multiple: true, include_blank: true, size: 6 %>
        </div>
      </div>
    </div>
  </div> <!-- /row -->

  <!-- advanced search options -->
  <div class="row">
    <div class="collapse" id="collapseMore">
      <div class="well">

        <div class="row">
          <div class="col-sm-3">
            <div class="form-group">
              <%= label_tag "format", "Format" %>
              <%= select_tag "format", options_from_collection_for_select(ImageFormat.sorted, "id", "name", params["format"]), class: "form-control", multiple: true, include_blank: true %>
            </div>
          </div>
          <% if !SETTINGS["hide_sensitive_image_records"] %>
            <div class="col-sm-3">
              <div class="form-group">
                <%= label_tag "human_remain", "Human Remains?" %>
                <%= select_tag "human_remain", options_from_collection_for_select(ImageHumanRemain.sorted, "id", "name", params["human_remain"]), class: "form-control", multiple: true, include_blank: true %>
              </div>
            </div>
          <% end %>
          <div class="col-sm-3">
            <div class="form-group">
              <%= label_tag "orientation", "Orientation" %>
              <%= select_tag "orientation", options_from_collection_for_select(ImageOrientation.sorted, "id", "name", params["orientation"]), class: "form-control", multiple: true, include_blank: true %>
            </div>
          </div>
          <div class="col-sm-3">
            <div class="form-group">
              <%= label_tag "quality", "Quality" %>
              <%= select_tag "quality", options_from_collection_for_select(ImageQuality.sorted, "id", "name", params["quality"]), class: "form-control", multiple: true, include_blank: true %>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-sm-3">
            <div class="form-group">
              <%= label_tag "box", "Box" %>
              <%= select_tag "box", options_from_collection_for_select(ImageBox.sorted, "id", "name", params["box"]), class: "form-control", multiple: true, include_blank: true %>
            </div>
          </div>
          <div class="col-sm-3">
            <div class="form-group">
              <%= label_tag "creator", "Creator" %>
              <%= select_tag "creator", options_from_collection_for_select(ImageCreator.sorted, "id", "name", params["creator"]), class: "form-control", multiple: true, include_blank: true %>
            </div>
          </div>
        </div>

      </div> <!-- /well -->
    </div> <!-- /collapse -->
  </div> <!-- /row -->

  <div class="row">
    <div class="col-md-4">
      <button class="btn btn-info" type="button"
        data-toggle="collapse" data-target="#collapseMore"
        aria-expanded="false" aria-controls="collapseMore">
        More Options
      </button>
      <%= render partial: "partials/clear_search", locals: { path: gallery_path } %>
      <%= submit_tag("Search", :class => "btn btn-primary") %>
    </div>
    <div class="col-md-7 pagination_container pull-right">
      <%= will_paginate @images %>
    </div>
  </div>
<% end %>

<p>Found <%= pluralize(@result_num, "image") %></p>


<% @images.each_slice(4) do |img_set| %>
  <div class="row gallery_row">
    <% img_set.each do |img| %>
      <div class="col-sm-3">
        <%= link_to image_path(img.image_no), class: "gallery_link" do %>
          <div class="gallery_entry">
            <span class="image_img">
              <%= image_display(img, thumb: true) %>
            </span>
            <ul class="gallery_info">
              <li><strong>Number:</strong> <%= img.image_no %></li>
              <li><strong>Units:</strong> <%= img.unit_list.join("; ") %></li>
              <li><strong>Comments:</strong> <%= img.comments %></li>
              <li><strong>Format:</strong> <%= img.format %></li>
              <% if !SETTINGS["hide_sensitive_image_records"] %>
                <li><strong>Human Remains:</strong> <%= img.human_remain %></li>
              <% end %>
              <li><strong>Subjects:</strong> <%= img.subject_list.join("; ") %></li>
            </ul>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

<div class="pagination_container">
  <%= will_paginate @images %>
</div>

app/views/image/show.html.erb
<h2>Image <%= @image.image_no %> <small>[<a href="#gallery_metadata">See data about image</a>]</small></h2>

<div class="image_display">
  <%= image_display(@image) %>
</div>

<div class="clearfix"></div>
<p><a href="<%= iiif_path(@image) %>" target="_blank">Download Image</a></p>

<div class="row gallery_metadata" id="gallery_metadata">
  <div class="col-md-6">
    <h2>Image Information</h2>
    <ul>
      <li>Number: <%= @image.image_no %></li>
      <li>Units:
        <% @image.unit_list.each do |u| %>
          <%= link_to u, unit_path(u) %>
        <% end %>
      </li>
      <li>Comments: <%= @image.comments %></li>
      <li>Format: <%= @image.format %></li>
      <% if !SETTINGS["hide_sensitive_image_records"] %>
        <li>
          Human Remains: <%= @image.human_remain %>
        </li>
      <% end %>
      <li>Subjects: <%= @image.subject_list.join("; ") %></li>
      <!-- TODO Features or Strata here? -->
      <li>Features: <%= @image.features.size %></li>
    </ul>
  </div>

  <div class="col-md-6">
    <h2>More Information</h2>
    <ul>
      <li>Box: <%= @image.box %></li>
      <li>Creator: <%= @image.creator %></li>
      <li>Data Entry: <%= @image.entered_by %></li>
      <li>Date: <%= @image.date %></li>
      <li>Depth Begin: <%= @image.depth_begin %></li>
      <li>Depth End: <%= @image.depth_end %></li>
      <li>Grid EW: <%= @image.grid_ew %></li>
      <li>Grid NS: <%= @image.grid_ns %></li>
      <li>Notes: <%= @image.notes %></li>
      <li>Orientation: <%= @image.orientation %></li>
      <li>Quality: <%= @image.quality %></li>
      <li>Signi Art No: <%= @image.sa_no %></li>
      <li>Site: <%= @image.site %></li>
      <li>Storage Location: <%= @image.storage_location %></li>
      <li>Zones: <%= @image.zone_list.join("; ") %></li>
    </ul>
  </div>
</div>