config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/', to: 'static#index', as: :home

  # Documents
  get '/documents', to: 'document#index', as: :documents
  get '/documents/unit/:unit(/:type)', to: 'document#unit',
      as: :documents_unit

  # Errors
  get '/404', to: 'errors#not_found'
  get '/422', to: 'errors#unacceptable'
  get '/500', to: 'errors#internal_error'

  # Explore
  get '/explore', to: 'explore#index', as: :explore
  get '/explore/map', to: 'explore#map', as: :map
  get '/explore/units', to: 'explore#units', as: :units
  get '/explore/unit/:number', to: 'explore#unit_summary', as: :unit
  get '/explore/unit/:number/overview', to: 'explore#unit_overview',
      as: :unit_overview
  get '/explore/unit/:number/images', to: 'explore#unit_images',
      as: :unit_images
  get '/explore/unit/:number/documents', to: 'explore#unit_documents',
      as: :unit_documents
  get '/explore/unit/:number/strata', to: 'explore#unit_strata',
      as: :unit_strata
  get '/explore/unit/:number/associated', to: 'explore#unit_associated',
      as: :unit_associated
  get '/explore/zone/:number', to: 'explore#zone', as: :search_zone

  # Images
  get '/gallery', to: 'image#index', as: :gallery
  get '/gallery/:number', to: 'image#show', as: :image

  # Query
  get '/query', to: 'query#index', as: :query
  get '/query/other', to: 'query#other', as: :query_other
  get '/query/:category', to: 'query#category', as: :query_category
  get '/query/:category/:subcat(/:table)', to: 'query#form', as: :query_form
  get '/query/:category/:subcat/:table/results', to: 'query#results',
      as: :query_results

  # Static Pages
  get '/about', to: 'static#about', as: :about
  get '/about/:name', to: 'static#about_sub', as: :about_sub
  get '/native-descendants', to: 'static#descendants', as: :descendants

end

app/controllers/explore_controller.rb
class ExploreController < ApplicationController
  before_action :set_section
  before_action :get_unit
  skip_before_action :get_unit, only: [:index, :map, :units, :zone], raise: false

  def index
  end

  def map
    @subsection = "map"
  end

  def units
    @subsection = "units"
    @unit_occs = Occupation.includes(:units)
                   .where.not(units: { occupation_id: nil })
                   .sorted

    units = Unit.includes(
      :inferred_function,
      :type_description,
      :occupation,
    )

    # text searches
    units = units.where("unit_no LIKE ?", "%#{params['unit_no']}%") if present?(params["unit_no"])
    units = units.where("other_description LIKE ?", "%#{params['other_description']}%") if present?(params["other_description"])
    units = units.where("units.comments LIKE ?", "%#{params['comments']}%") if present?(params["comments"])
    units = units.joins(:strata).where("strata.strat_all LIKE ?", "%#{params['strata']}%") if present?(params["strata"])

    # basic joins
    units = add_to_query(units, :excavation_statuses, params["excavation_status"], :excavation_status)
    units = add_to_query(units, :inferred_functions, params["inferred_function"], :inferred_function, false)
    units = add_to_query(units, :intact_roofs, params["intact_roof"], :intact_roof)
    units = add_to_query(units, :irregular_shapes, params["irregular_shape"], :irregular_shape)
    units = add_to_query(units, :salmon_sectors, params["salmon_sector"], :salmon_sector)
    units = add_to_query(units, :stories, params["story"], :story)
    units = add_to_query(units, :type_descriptions, params["type_description"], :type_description, false)
    units = add_to_query(units, :unit_classes, params["unit_class"], :unit_class)
    units = add_to_query(units, :occupations, params["occupation"], :occupation, false)
    units = add_to_query(units, :zones, params["zone"], :zone)

    # left joins where not null
    if present?(params["items"])
      params["items"].each do |item|
        units = units.includes(item).where.not(item => { :id => nil })
      end
    end

    @result_num = units.size
    @units = units.sorted.paginate(:page => params[:page], :per_page => 20)
  end

  def unit_associated
    @subsection = "units"
    @selected = "associated"
  end

  def unit_documents
    @subsection = "units"
    @selected = "documents"

    @res = []

    doc_types = @unit.document_types.pluck(:id)
    doc_types.each do |dt|
      @res << Document.joins(:document_type, :units)
              .where("units.unit_no = ?", @unit.unit_no)
              .where(document_type: dt)
              .sorted
              .first
    end
    @document_count = @unit.documents.count
  end

  def unit_images
    @subsection = "units"
    @selected = "images"
    @images = @unit.images.where(file_exists: true)
    @images_display = @images.sorted.limit(8)
  end

  def unit_overview
    @subsection = "units"
    @selected = "overview"
  end

  def unit_strata
    @subsection = "units"
    @selected = "strata"

    @strata = @unit.strata.includes(:features, :occupation, :strat_type)
  end

  def unit_summary
    @subsection = "units"
    @selected = "summary"
  end

  def zone
    @subsection = "units"
    # pad zones with appropriate number of zeroes, despite P / BW codes
    @zone_no = params["number"].rjust(3, "0")
    if @zone_no[/[A-Z]/]
      num = @zone_no[/\d*/]
      if num.length < 3
        @zone_no = @zone_no.gsub(num, num.rjust(3, "0"))
      end
    end
    @zone = Zone.find_by(name: @zone_no)
    if @zone
      @units = @zone.units.sorted
      # if linked to from the chaco occupation map, filter the units
      @all_count = @units.count
      if params["occupation"] == "chaco"
        @units = @units.joins(:occupation)
          .where("occupations.name": ["Chacoan", "Mixed Chacoan and San Juan"])
        @is_filtered = @all_count != @units.count
      end
    end
  end


  private

  # TODO combine this with the images search when the branches are merged
  # essentially creating: images.where(:where_rel => { :id => param }).joins(:relationship)
  # most of the time relationship is the same as where_rel but depends on model design
  def add_to_query query_obj, where_rel, param, relationship=where_rel, joins=true
    if present?(param)
      query_obj = query_obj.where(where_rel => { :id => param })
      query_obj = query_obj.joins(relationship) if joins
    end
    return query_obj
  end

  def get_unit
    num = params["number"].gsub("%2F", "/")
    @unit = Unit.sorted.where(unit_no: num).first
  end

  def set_section
    @section = "explore"
  end
end

app/helpers/explore_helper.rb
module ExploreHelper

  def item_radio_list
    %w[
      bone_tools
      ceramics
      ceramic_claps
      ceramic_inventories
      ceramic_vessels
      eggshells
      faunal_artifacts
      faunal_inventories
      lithic_debitages
      lithic_inventories
      lithic_tools
      obsidian_inventories
      ornaments
      perishables
      pollen_inventories
      soils
      tree_rings
      wood_inventories
    ]
  end

  def related_units(unit)
    rel = []
    units = unit.zone.units
    if units.count > 1
      nos = units.pluck(:unit_no)
      nos.delete(unit.unit_no)
      rel = nos.map { |u| link_to u, unit_path(u) }
    end
    rel
  end

end

app/views/explore/_item_radio_buttons.html.erb
<% item_radio_list.each do |item| %>
  <li>
    <%= label_tag "items_#{item}", item.titleize %>
    <% selected = params["items"].present? && params["items"].include?(item) %>
    <%= check_box_tag "items[]", item, selected, id: "items_#{item}" %>
  </li>
<% end %>

app/views/explore/_unit_tabs.html.erb
<!-- Nav tabs -->
<ul class="nav nav-tabs" role="tablist">
  <li role="presentation" class="<%= active?("summary", @selected) %>">
    <%= link_to "Summary", unit_path(@unit.unit_no) %>
  </li>
  <li role="presentation" class="<%= active?("overview", @selected) %>">
    <%= link_to "Overview", unit_overview_path(@unit.unit_no) %>
  </li>
  <li role="presentation" class="<%= active?("images", @selected) %>">
    <%= link_to "Images", unit_images_path(@unit.unit_no) %>
  </li>
  <% if @unit.documents.count > 0 %>
    <li role="presentation" class="<%= active?("documents", @selected) %>">
      <%= link_to "Documents", unit_documents_path(@unit.unit_no) %>
    </li>
  <% end %>
  <li role="presentation" class="<%= active?("strata", @selected) %>">
    <%= link_to "Strata", unit_strata_path(@unit.unit_no) %>
  </li>
  <li role="presentation" class="<%= active?("associated", @selected) %>">
    <%= link_to "Associated Objects", unit_associated_path(@unit.unit_no) %>
  </li>
</ul>

app/views/explore/index.html.erb
<h2>Explore Salmon Pueblo</h2>

<p>Using the interactive map below, you can browse excavation information by clicking on a particular excavation context. You can also toggle between the Chacoan and post-Chacoan (San Juan) occupations of the site and show/hide excavation trenches. </p>

<p>The “Browse Units” page will take you to a searchable list of excavation contexts. </p>

</div> <!-- /container -->

<div class="container-fluid">

<div class="row explore_choices">
  <div class="col-sm-6">
    <%= link_to map_path, class: "content explore_callout1 home_callout" do %>
      <div class="explore_inner">
        <div class="row">
          <div class="col-md-9 col-md-offset-3">
            <div class="inner_content">
              <h4>Interactive Map</h4>
              <p>browse the excavation information by clicking on a particular room, unit or excavation context</p>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div><!-- /col -->
  <div class="col-sm-6">
    <%= link_to units_path, class: "content explore_callout2 home_callout" do %>
      <div class="explore_inner">
        <div class="row">
          <div class="col-md-9 ">
            <div class="inner_content">
              <h4>Browse Units</h4>
              <p>Search and browse by Units</p>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div><!-- /col -->
</div><!-- /row -->

app/views/explore/map.html.erb
<%= javascript_include_tag 'svg-pan-zoom' %>
<%= stylesheet_link_tag 'maps' %>

<script>
	$(function () {
    $('[data-toggle="popover"]').popover()
  })
</script>

<p>When you select an individual excavation unit, the map will take you to a new page with summary information and panel links to specific units defined for that context.  Once you select a unit, you can browse various categories of available information. </p>

<p>The map tools allow you to toggle between two different versions of Salmon Pueblo: the initial Chaco occupation and the later San Juan occupation.  The Chaco map will provide access only to those units which date to the Chaco era (1090-1125 CE).  The San Juan map will return all units defined for that  context (both Chacoan and post-Chacoan).  </p>

<div class="map_controls">
  <form lpformnum="1">
    <div class="row">
      <div class="col-sm-3">
        <h3>Map Controls:</h3>
      </div><!-- /col -->
      <div class="col-sm-4 map_trench_controls">
        <strong>Trenches:</strong>
        <div class="btn-group" data-toggle="buttons">
          <label class="btn btn-primary active" onclick="toggle_trenches_on()">
            <input type="radio" name="options" id="toggle_salmon_occ" autocomplete="off" checked > Show
          </label>
          <label class="btn btn-primary" onclick="toggle_trenches_off()">
            <input type="radio" name="options" id="toggle_chaco_occ" autocomplete="off" > Hide
          </label>
        </div>
      </div><!-- /col -->

      <div class="col-sm-5">
        <strong>Occupation:</strong>
        <div class="btn-group" data-toggle="buttons">
          <label class="btn btn-primary active" onclick="toggle_salmon_display()">
            <input type="radio" name="options" id="toggle_salmon_occ" autocomplete="off" checked > San Juan
          </label>
          <label class="btn btn-primary" onclick="toggle_chaco_display()">
            <input type="radio" name="options" id="toggle_chaco_occ" autocomplete="off" > Chaco
          </label>
        </div>

        <span class="glyphicon glyphicon-question-sign map_occupation_help" aria-hidden="true" data-toggle="popover" data-content="Text for this pop-up: The Chaco-era map will take you to units identified with the Chacaon occupation. The San Juan-era map will show you all units from both occupations."></span>
      </div><!-- /col -->

    </div><!-- /row -->
  </form>
</div><!-- /map_controls -->

</div><!-- /container -->

<div class="container-fluid">
  <div id="map_container">
    <%= render "svg" %>
  </div>
</div>

<%= javascript_include_tag 'map_zoom' %>

app/views/explore/unit_images.html.erb
<h2><%= @unit.unit_no %></h2>

<%= render "unit_tabs" %>

<div role="tabpanel" class="tab-pane" id="images">
  <!-- TODO could move this and image#index version into partial? -->
  <div class="row">
    <% if @images.present? %>
       <%= link_to gallery_path({ :unit => @unit.id }), class: "btn btn-primary btn-lg explore_see_more" do %>
         View <%= pluralize @images.count, "image" %> images 
         for <%= @unit.unit_no %> in the Image Gallery 
         <span class="glyphicon glyphicon-arrow-right" aria-hidden="true"></span>
       <% end %>

      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Example Images</h3>
        </div>
        <div class="panel-body">
          <% @images_display.each_slice(4) do |img_set| %>
            <div class="row">
              <% img_set.each do |img| %>
                <div class="col-xs-3 explore_sample_image">
                  <p><%= img.image_no %> <%= img.format %></p>
                  <%= link_to image_path img.image_no do %>
                    <%= image_display(img, thumb: true) %>
                  <% end %>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
      </div><!-- /panel -->
    <% else %>
      No images associated with this unit.
    <% end %>
  </div><!-- /row -->
</div><!-- /tabpanel -->

app/views/explore/unit_overview.html.erb
<h2><%= @unit.unit_no %></h2>

<%= render "unit_tabs" %>

<div role="tabpanel" class="tab-pane" id="overview">
  <div class="row">
    <div class="col-md-6">
      <h3>Physical Description</h3>
      <ul>
        <li><strong>Class:</strong> <%= @unit.unit_class.name if @unit.unit_class %></li>
        <li><strong>Length:</strong> <%= @unit.length %></li>
        <li><strong>Width:</strong> <%= @unit.width %></li>
        <li><strong>Floor Area:</strong> <%= @unit.floor_area %></li>
        <li><strong>Sector:</strong> <%= @unit.salmon_sector.name if @unit.salmon_sector %></li>
        <li><strong>Stories:</strong> <%= @unit.story.name if @unit.story %></li>
        <li><strong>Intact Roof:</strong> <%= @unit.intact_roof.name if @unit.intact_roof %></li>
        <li><strong>Type:</strong> <%= @unit.salmon_type_code %></li>
        <li><strong>Type Description:</strong> <%= @unit.type_description.name if @unit.type_description %></li>
        <li><strong>Irregular Shape:</strong> <%= @unit.irregular_shape.name if @unit.irregular_shape %></li>
      </ul>
    </div>
    <div class="col-md-6">
      <h3>Other Information</h3>
      <ul>
        <li><strong>Occupation:</strong> <%= @unit.occupation.name if @unit.occupation %></li>
        <li><strong>Excavation Status:</strong> <%= @unit.excavation_status.name if @unit.excavation_status %></li>
        <li><strong>Associated Strata:</strong> <%= pluralize @unit.strata.size, "stratum" %></li>
        <li><strong>Inferred Function:</strong> <%= @unit.inferred_function.name if @unit.inferred_function %></li>
        <li><strong>Other Description:</strong> <%= @unit.other_description if @unit.other_description %></li>
        <li><strong>Comments:</strong> <%= @unit.comments %></li>
        <% if related_units(@unit).present? %>
          <li>
            <strong>Related Unit(s):</strong>
            <%= sanitize(related_units(@unit).join("; ")) %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/explore/unit_strata.html.erb
<h2><%= @unit.unit_no %></h2>

<%= render "unit_tabs" %>

<div role="tabpanel" class="tab-pane" id="strata">
  <div class="table-responsive">
    <table class="table table-striped table-condensed ">
      <tr>
        <th>Stratum Number</th>
        <th>Stratum Type</th>
        <th>Features</th>
        <th>Occupation</th>
      </tr>
      <% @strata.each do |stratum| %>
        <tr>
          <td><%= stratum.strat_all %></td>
          <td><%= stratum.strat_type.name if stratum.strat_type %></td>
          <td><%= stratum.features.map {|f| f.feature_no }.join("; ") %></td>
          <td><%= stratum.occupation.name if stratum.occupation %></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/explore/unit_summary.html.erb
<h2><%= @unit.unit_no %></h2>

<%= render "unit_tabs" %>

<div role="tabpanel" class="tab-pane active" id="summary">
  <div class="row">
    <div class="col-md-8 buffer-bottom">
      <p class="lead"><%= sanitize @unit.description %></p>
    </div>
    <div class="col-md-4 explore_summary_mm">
      <% if @unit.media_maps.present? %>
        <%= image_tag iiif_path(@unit.media_maps.first, "!300,300") %>
      <% end %>
    </div>
  </div>
</div>
</div> <!-- /tab-content -->

app/views/explore/units.html.erb
<h2>Search All Units</h2>

<%= form_tag units_path, :method => "get",
  id: "unit-search-form", role: "form" do %>
  <%= hidden_field_tag "sort", params["sort"] %>

  <div class="row">
    <!-- location -->
    <div class="col-md-3">
      <div class="form-group">
        <%= label_tag "unit_no", "Unit Number (e.g. \"001\", \"BW\")" %>
        <%= text_field_tag "unit_no", params["unit_no"], class: "form-control" %>
      </div>
      <div class="form-group float-bottom">
        <%= label_tag "unit_class", "Unit Class" %>
        <%= select_tag "unit_class", options_from_collection_for_select(UnitClass.sorted, "id", "name", params["unit_class"]), class: "form-control", multiple: true, include_blank: true %>
      </div>
    </div>

    <!-- description -->
    <div class="col-md-3">
      <div class="form-group">
        <%= label_tag "occupation", "Occupation" %>
        <%= select_tag "occupation", options_from_collection_for_select(@unit_occs, "id", "name", params["occupation"]), class: "form-control", multiple: true, include_blank: true %>
      </div>
      <div class="form-group">
        <%= label_tag "irregular_shape", "IrregularShape" %>
        <%= select_tag "irregular_shape", options_from_collection_for_select(IrregularShape.sorted, "id", "name", params["irregular_shape"]), class: "form-control", multiple: true, include_blank: true %>
      </div>
    </div>

    <!-- other description -->
    <div class="col-md-3">
      <div class="form-group">
        <%= label_tag "story", "Story" %>
        <%= select_tag "story", options_from_collection_for_select(Story.sorted, "id", "name", params["story"]), class: "form-control", multiple: true, include_blank: true %>
      </div>
      <div class="form-group">
        <%= label_tag "intact_roof", "IntactRoof" %>
        <%= select_tag "intact_roof", options_from_collection_for_select(IntactRoof.sorted, "id", "name", params["intact_roof"]), class: "form-control", multiple: true, include_blank: true %>
      </div>
    </div>

    <!-- function -->
    <div class="col-md-3">
      <div class="form-group">
        <%= label_tag "inferred_function", "Inferred Function" %>
        <%= select_tag "inferred_function", options_from_collection_for_select(InferredFunction.sorted, "id", "name", params["inferred_function"]), class: "form-control", multiple: true, include_blank: true %>
      </div>
      <div class="form-group">
        <%= label_tag "excavation_status", "Excavation Status" %>
        <%= select_tag "excavation_status", options_from_collection_for_select(ExcavationStatus.sorted, "id", "name", params["excavation_status"]), class: "form-control", multiple: true, include_blank: true %>
      </div>
    </div>

  </div> <!-- /row -->

  <!-- COLLAPSED SEARCH OPTIONS -->
    <div class="collapse" id="collapseMore">
      <div class="well">
        <div class="row">

        <!-- location -->
          <div class="col-md-3">
            <div class="form-group">
              <%= label_tag "zone", "Zone" %>
              <%= select_tag "zone", options_from_collection_for_select(Zone.sorted, "id", "name", params["zone"]), class: "form-control", multiple: true, include_blank: true %>
            </div>
            <div class="form-group">
              <%= label_tag "salmon_sector", "Salmon Sector" %>
              <%= select_tag "salmon_sector", options_from_collection_for_select(SalmonSector.sorted, "id", "name", params["salmon_sector"]), class: "form-control", multiple: true, include_blank: true %>
            </div>
          </div>

          <!-- unit type description -->
          <div class="col-md-3">
            <div class="form-group">
              <%= label_tag "type_description", "Type Description" %>
              <%= select_tag "type_description", options_from_collection_for_select(TypeDescription.sorted, "id", "name", params["type_description"]), class: "form-control", multiple: true, include_blank: true %>
            </div>
          </div>

          <!-- ? -->
          <div class="col-md-3">
            <div class="form-group">
              <%= label_tag "strata", "Strata (e.g. \"B-1-2\")" %>
              <%= text_field_tag "strata", params["strata"], class: "form-control" %>
            </div>
          </div>

          <!-- comments -->
          <div class="col-md-3">
            <div class="form-group">
              <%= label_tag "other_description", "Other Description (e.g. \"interstitial\")" %>
              <%= text_field_tag "other_description", params["other_description"], class: "form-control" %>
            </div>
            <div class="form-group">
              <%= label_tag "comments", "Comments (e.g. \"interstitial\")" %>
              <%= text_field_tag "comments", params["comments"], class: "form-control" %>
            </div>
          </div>
        </div> <!-- /row -->

    </div> <!-- /well -->
  </div>

  <div class="row">
    <div class="collapse" id="collapseItems">
      <div class="well">
        <h4>Return only units with the following items: <small>(query may take some time when selecting multiple items, please be patient)</small></h4>
        <div class="form-group">
          <ul id="unit_search_list">
            <%= render "item_radio_buttons" %>
          </ul>
        </div>
      </div> <!-- /well -->
    </div> <!-- /collapse -->
  </div> <!-- /row -->

  <div class="row">
    <div class="col-md-6"> 
      <button class="btn btn-info" type="button"
      data-toggle="collapse" data-target="#collapseMore"
      aria-expanded="false" aria-controls="collapseMore">
        More Options
      </button>
      <button class="btn btn-info" type="button"
      data-toggle="collapse" data-target="#collapseItems"
      aria-expanded="false" aria-controls="collapseItems">
        <% if params["items"].present? && !params["items"].empty? %>
          <span class="glyphicon glyphicon-warning-sign"></span>
        <% end %>
        Limit by Items in Unit
      </button>
      <%= render :partial => "partials/clear_search", :locals => { :path => units_path } %>
      <%= submit_tag "Search", :class => "btn btn-primary" %>
    </div>
    <div class="col-md-6 pagination_container">
      <%= will_paginate @units %>
    </div>
  </div> <!-- /row -->

  <p>Found <%= pluralize @result_num, "result" %></p>

  <% if params["items"].present? && !params["items"].empty? %>
    <span class="glyphicon glyphicon-warning-sign"></span>
    Note that units shown are limited by items within them. See above
  <% end %>

  <% @units.each_slice(4) do |unit_set| %>
    <div class="row gallery_row">
      <% unit_set.each do |unit| %>
        <div class="col-sm-3">
          <%= link_to unit_path(unit.unit_no), class: "gallery_link" do %>
            <div class="gallery_entry">
              <h3><%= unit.unit_no %></h3>
              <ul class=" gallery_info">
                <li><strong>Occupation:</strong> <%= unit.occupation.name if unit.occupation %></li>
                <li><strong>Type:</strong> <%= unit.type_description.name if unit.type_description %></li>
                <li><strong>Inferred Function:</strong> <%= unit.inferred_function.name if unit.inferred_function %></li>
                <li><strong>Number of Images:</strong> <%= unit.images.size %></li>
              </ul>
            </div>
          <% end %>
        </div>
      <% end %>
    </div><!-- /row -->
  <% end %>
<% end %>

<div class="pagination_container">
  <%= will_paginate @units %>
</div>

app/views/explore/zone.html.erb
<% if @zone %>
  <h2><%= @zone.name %></h2>

  <div class="row">
    <div class="col-md-6 buffer-bottom">
      <%= sanitize @zone.description %>
    </div>
    <div class="col-md-6">
      <% if params["occupation"] == "chaco" %>
        <%= image_tag "home_explore_chaco.jpg", class: "explore_zone_image" %>
      <% else %>
        <%= image_tag "home_explore.jpg", class: "explore_zone_image" %>
      <% end %>
    </div>
  </div>

  <% if params["occupation"] == "chaco" && @is_filtered %>
    <p>
      Displaying a filtered list of units present during the Chacoan occupation.
      <%= link_to search_zone_path(@zone.name) do %>
        View <%= pluralize @all_count, "unit" %> regardless of occupation
      <% end %>
    </p>
  <% end %>
  <% @units.each_slice(3) do |unit_set| %>
    <div class="row">
      <% unit_set.each do |unit| %>
        <div class="col-md-4">
          <%= link_to unit_path(unit.unit_no) do %>
            <div class="panel panel-default">
              <div class="panel-heading">
                <h3 class="panel-title">
                  <%= unit.unit_no %>
                  <% if unit.occupation.present? %>
                    (<%= unit.occupation.name %>)
                  <% end %>
                </h3>
              </div>
              <div class="panel-body">
                <ul>
                  <li><strong>Class:</strong> <%= unit.unit_class.name if unit.unit_class %></li>
                  <li><strong>Excavation Status:</strong> <%= unit.excavation_status.name if unit.excavation_status %></li>
                  <li><strong>Type:</strong> <%= unit.type_description.name if unit.type_description %>
                  <li><strong>Other Description:</strong> <%= unit.other_description %></li>
                  <% if unit.media_maps.first %>
                    <%= image_tag iiif_path(unit.media_maps.first, SETTINGS["thumbnail_size"]) %>
                  <% end %>
                </ul>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>
<% else %>
  <h1>No zone found for <%= @zone_no %></h1>
<% end %>