config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/', to: 'static#index', as: :home

  # Documents
  get '/documents', to: 'document#index', as: :documents
  get '/documents/unit/:unit(/:type)', to: 'document#unit',
      as: :documents_unit

  # Errors
  get '/404', to: 'errors#not_found'
  get '/422', to: 'errors#unacceptable'
  get '/500', to: 'errors#internal_error'

  # Explore
  get '/explore', to: 'explore#index', as: :explore
  get '/explore/map', to: 'explore#map', as: :map
  get '/explore/units', to: 'explore#units', as: :units
  get '/explore/unit/:number', to: 'explore#unit_summary', as: :unit
  get '/explore/unit/:number/overview', to: 'explore#unit_overview',
      as: :unit_overview
  get '/explore/unit/:number/images', to: 'explore#unit_images',
      as: :unit_images
  get '/explore/unit/:number/documents', to: 'explore#unit_documents',
      as: :unit_documents
  get '/explore/unit/:number/strata', to: 'explore#unit_strata',
      as: :unit_strata
  get '/explore/unit/:number/associated', to: 'explore#unit_associated',
      as: :unit_associated
  get '/explore/zone/:number', to: 'explore#zone', as: :search_zone

  # Images
  get '/gallery', to: 'image#index', as: :gallery
  get '/gallery/:number', to: 'image#show', as: :image

  # Query
  get '/query', to: 'query#index', as: :query
  get '/query/other', to: 'query#other', as: :query_other
  get '/query/:category', to: 'query#category', as: :query_category
  get '/query/:category/:subcat(/:table)', to: 'query#form', as: :query_form
  get '/query/:category/:subcat/:table/results', to: 'query#results',
      as: :query_results

  # Static Pages
  get '/about', to: 'static#about', as: :about
  get '/about/:name', to: 'static#about_sub', as: :about_sub
  get '/native-descendants', to: 'static#descendants', as: :descendants

end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_site_list.html.erb
<table><tr>
	<% 
	@sites = Site.where("popular_name is not null and popular_name != '' and display=true").order('popular_name asc')
	str = ''
	x=0
	%>
	<% @sites.each do |site| %>
	
	  	<td valign="top"><input type="checkbox" value="<%= site.id %>" id="<%= site.id %>" name="site"><label for="<%= site.id %>"><%= site.popular_name %></label></td>
		<% x += 1 %>
		<% if x > 2 %>	
			</tr><tr>
			<% x=0 %>
		<% end %>
	<% end %>
</tr></table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><%= title_display %></title>

    <link href="https://fonts.googleapis.com/css?family=Jura:400,600,700" rel="stylesheet">

    <%= render "partials/google_analytics" %>
    <%= render "partials/internet_explorer_support" %>
    <%= render 'application/favicon' %>

  </head>


  <body class="body_<%= params[:controller] %> body_<%= params[:action] %> <% if current_page? home_path %>home_page<% end %>">

    <header class="body_head">
      <%# if statement to only show on home page %>
      <% if current_page?(home_path) %>
        <div class="header_top">
          <div class="header_stuff container">
            <div class="site_logo_container">
              <div class="site_image">
                <%= image_tag 'effigy3.png' %>
              </div>
              <h1 class="header_words header_words_nav">
                  <span class="head_sp">Salmon Pueblo</span>
                  <span class="head_arc">Archaeological Research Collection</span>
              </h1>
            </div><!-- site_logo_container -->
          </div><!-- /header_stuff -->
        </div><!-- /header_top -->
      <% end %>
      <%#  END if statement %>

      <div class="navbar navbar-default sparc_navbar">
        <div class="container">

        <%#  if statement to show everywhere BUT home page %>
        <% if !current_page?(home_path) %>
          <h1 class="header_words">
            <%= link_to home_path, class: "home_links" do %>
              <span class="head_sp">Salmon Pueblo</span>
              <span class="head_arc">Archaeological Research Collection</span>
            <% end %>
          </h1>
        <% end %>
        <%#  END if statement %>

          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          </div>
          <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
              <% section = @section || params["controller"] %>
              <!-- <li class="<%#= active?(home_path) %>">
                <%#= link_to "SPARC Home", home_path %>
              </li> -->
              <li class="<%= active?("explore", section) %>">
                <%= link_to "Explore Pueblo", explore_path %>
              </li>
              <li class="<%= active?("query", section) %>">
                <%= link_to "Query Data", query_path %>
              </li>
              <li class="<%= active?("documents", section) %>">
                <%= link_to "Documents", documents_path %>
              </li>
              <li class="<%= active?("images", section) %>">
                <%= link_to "Image Gallery", gallery_path %>
              </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li class="<%= active?("descendants", section) %>">
                <%= link_to "Native Descendants", descendants_path %>
              </li>
              <li class="<%= active?("about", section) %>">
                <%= link_to "About", about_path %>
              </li>
            </ul>
          </div> <!-- /navbar-collapse -->
        </div>
      </div>
    </header>

    <div class="container main_content">
      <%= yield %>
    </div>

    <footer class="project_footer">
      <div class="container">
        <p><%= link_to "How To Cite", about_sub_path(name: "how-to-cite"), :class => '' %></p>
        <p>The <em>Salmon Pueblo Archaeological Research Collection</em> created by the Center for Digital Research in the Humanities with funding from the National Endowment for the Humanities and in partnership with Archaeology Southwest, the Institute for Advanced Technology in the Humanities, and the San Juan County Archaeological Research Center and Library - Salmon Ruins. Distributed under a <a href="https://creativecommons.org/licenses/by-nc-nd/4.0/">Creative Commons License</a>.</p>
        <div class="row footer_logos text-center">
          <div class="col-md-4">
            <div class="logo_sr">
              <a href="https://www.salmonruins.com/archaeology-firm.html" alt="san Juan Museum Association">
                <%= image_tag 'logo_sr.gif' %>
              </a>
            </div>
          </div>
          <div class="col-md-4">
            <div class="logo_neh">
              <a href="https://www.neh.gov/" alt="The National Endowment for the Humanities">
                <%= image_tag 'logo_neh.gif' %>
              </a>
            </div>
            <div class="logo_as">
              <a href="https://www.archaeologysouthwest.org/" alt="Archaeology Southwest">
                <%= image_tag 'logo_archaeology_southwest.gif' %>
              </a>
            </div>
          </div>
          <div class="col-md-4">
            <div class="logo_unl">
              <a href="https://cdrh.unl.edu/" alt="The Center for Digital Research in the Humanities at the University of Nebraska–Lincoln">
                <%= image_tag 'logo_unl.gif' %>
              </a>
            </div>
            <div class="logo_iath">
              <a href="http://www.iath.virginia.edu/" alt="The Institute for Advanced Technology in the Humanities at the University of Virginia">
                <%= image_tag 'logo_iath.gif' %>
              </a>
            </div>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>